config/routes.rb
Demarche::Application.routes.draw do
  resources :tickets
  resources :ticket_responses
  resources :requesters

  devise_for :users

  match 'tickets/close/:id' => 'tickets#close'
  
  match 'activity' => 'tickets#activity'
  

  root :to => 'tickets#activity'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  #https://github.com/EppO/rolify/wiki/Tutorial
  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end    
  end
end

app/models/requester.rb
class Requester < ActiveRecord::Base
  has_many :tickets
  has_many :ticket_responses
  attr_accessible :email_address, :name, :organization_id

  def self.find_or_create(attributes)
    Requester.where(attributes).first || Requester.create(attributes)
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  resourcify
  
  has_many :ticket_responses
  belongs_to :requester
  belongs_to :user
  attr_accessible :body, :requester_id, :subject, :messageid, :state
  
  validates_presence_of :requester_id, :messageid, :body
  validates_uniqueness_of :messageid
  
  before_validation :ensure_messageid
  after_create :send_initial
  
  state_machine :initial => :new do
    after_transition all => :closed, :do => :send_closed
    
    event :user_receive do
      transition :new => :answered
    end
    event :requester_receive do
      transition :answered => :need_response
    end
    event :close_ticket do
      transition all => :closed
    end

  end
  
  def send_initial
    TicketMailer.initial_response(self.requester, self).deliver
  end
  
  def send_closed
    TicketMailer.send_closed(self.requester, self).deliver
  end
  
  def ensure_messageid
    require 'digest'
    if self.messageid == nil
      self.messageid = Digest::SHA1.hexdigest(self.body+self.requester.email_address+Time.now.to_s)
    end
  end
      
  def self.import
    require 'digest'
    imap = Net::IMAP.new(ENV["IMAP_HOST"])
    imap.authenticate('LOGIN', ENV["IMAP_USERNAME"], ENV["IMAP_PASSWORD"])
    imap.examine('INBOX')
    imap.search(["UNSEEN"]).each do |message_id|
      msg = imap.fetch(message_id, "(ENVELOPE BODY[TEXT])")[0]
      envelope = msg.attr["ENVELOPE"]
      body = msg.attr["BODY[TEXT]"]
      subject = envelope.subject
      name = envelope.from[0].name
      from_email = envelope.from[0].mailbox + '@' + envelope.from[0].host
      tn = envelope.to.select {|v| v.mailbox[0..ENV["MAILBOX_NAME"].size] == "#{ENV["MAILBOX_NAME"]}+"}
      if tn != []
        ticket_number = tn.first.mailbox.split('+').last
      end
      requester = Requester.find_or_create(:email_address => from_email, :name => name)
      messageid = envelope.message_id || Digest::SHA1.hexdigest(body+from_email+envelope.date)
      if Ticket.exists?(ticket_number)
        Ticket.find(ticket_number).requester_receive
        TicketResponse.create(:ticket_id => ticket_number, :body => body, :requester_id => requester.id, :messageid => messageid)
      else
        self.create(:subject => subject, :body => body, :requester_id => requester.id, :messageid => messageid)
      end
    end
    imap.logout
    imap.disconnect
  end
end

app/models/ticket_response.rb
class TicketResponse < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :user
  belongs_to :requester
  
  attr_accessible :body, :requester_id, :ticket_id, :user_id, :messageid
  
  validates_uniqueness_of :messageid
  validates_presence_of :body
  
  before_validation :ensure_messageid
  after_save :send_response
  
  def ensure_messageid
    require 'digest'
    if self.messageid == nil
      self.messageid = Digest::SHA1.hexdigest(self.body+self.user.email+Time.now.to_s)
    end
  end
  
  def send_response
    if self.user
      self.ticket.user_receive
      TicketResponseMailer.response(self.body, self.requester, self.ticket, self.user).deliver
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  validates_uniqueness_of :email
  
  has_many :ticket_responses
  has_many :tickets
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/requesters_controller.rb
class RequestersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @requesters = Requester.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end
  
end

app/controllers/ticket_responses_controller.rb
class TicketResponsesController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    @ticketresponse = TicketResponse.new(params[:ticket_response])
    @ticketresponse.user_id = current_user.id
    
    respond_to do |format|
      if @ticketresponse.save
        format.html { redirect_to @ticketresponse.ticket, notice: 'Response was sent.' }
        format.json { render json: @ticketresponse, status: :created, location: @ticket }
      else
        format.html { redirect_to @ticketresponse.ticket, notice: 'Error sending response.'  }
        format.json { render json: @ticketresponse.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :authenticate_user!
  
  def close
    @ticket = Ticket.find(params[:id])
    @ticket.close_ticket
    
    respond_to do |format|
      format.html { redirect_to @ticket, notice: 'Ticket was closed.' }
      format.json { render json: @ticket }
    end
  end

  def activity
    tickets = Ticket.limit(5)
    responses = TicketResponse.limit(5)
    requesters = Requester.limit(5)
    users = User.limit(5)
    
    @stream = (tickets + responses + requesters + users).sort {|x,y| y.created_at <=> x.created_at }
        
    respond_to do |format|
      format.html
    end
  end
  
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
    @ticket_responses = @ticket.ticket_responses
    @ticket_response = TicketResponse.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  def create
    @ticket = Ticket.new(params[:ticket])
    @ticket.user_id = current_user.id

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ticket_response_helper.rb
module TicketResponseHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Demarche" %></title>
    <%= csrf_meta_tags %>

	<link href="http://fonts.googleapis.com/css?family=Corben:bold" rel="stylesheet" type="text/css">
	 <link href="http://fonts.googleapis.com/css?family=Nobile" rel="stylesheet" type="text/css">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Demarche</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Tickets", "/tickets"  %></li>
              <li><%= link_to "Requesters", "/requesters"  %></li>
			</ul>
				 <ul class="nav pull-right">
				  <% if user_signed_in? %>
					<li><span class="badge badge-important"><%= Ticket.where("state = ? or state = ?", 'new', 'need_response').count %></span></li>
					<li class="dropdown">
					  <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.email %>   <b class="caret"></b>
					  </a>
					  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
						<li><%= link_to "Preferences", edit_user_registration_path %></li>
						<li class="divider"></li>
					    <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
					  </ul>
					</div>
				  <% else %>
					<li><%= link_to "Log in", new_user_session_path %></li>
				  <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
             <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/requesters/index.html.erb
<h1>Requesters</h1>

<% if !@requesters.empty? %>
	<table class="table table-bordered">
	  <tr>
	    <th>Name</th>
	    <th>Email</th>
	    <th>Requests</th>
	  </tr>

	<% @requesters.each do |requester| %>
	  <tr>
	    <td><%= requester.name %></td>
	    <td><%= requester.email_address %></td>
	    <td><%= requester.tickets.count %></td>

	  </tr>
	<% end %>
	</table>
<% else %>
	No requesters
<% end %>

app/views/tickets/_form.html.erb
<%= form_for(@ticket, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label" for="inputRequester">Requester</label>
    <div class="controls">
	<%= f.select(:requester_id, Requester.all.collect {|a| [a.name, a.id]}, :html => {:id => 'inputRequester'}) -%>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputSubject">Subject</label>
    <div class="controls">
     <%= f.text_field :subject, :html => {:id => 'inputSubject'} %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputBody">Body</label>
    <div class="controls">
     <%= f.text_area :body, :html => {:id => 'inputBody'} %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit :class => 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/tickets/_response_form.erb
<%= form_for(@ticket_response) do |f| %>
  <% if @ticket_response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_response.errors.count, "error") %> prohibited this ticket from being sent:</h2>

      <ul>
      <% @ticket_response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body, :rows => 6 %>
  </div>
    <%= f.hidden_field :ticket_id, :value => @ticket.id %>
    <%= f.hidden_field :requester_id, :value => @ticket.requester_id %>
  <div class="actions">
	<div class="btn-group">
	  <%= f.submit "Send reply", :class => 'btn btn-success' %>
	    
	  <button class="btn">Action</button>
	  <button class="btn dropdown-toggle" data-toggle="dropdown">
	    <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
	    <li><a tabindex="-1" href="/tickets/close/<%= @ticket.id %>">Close</a></li>
	    <li><a tabindex="-1" href="#">Another action</a></li>
	    <li><a tabindex="-1" href="#">Something else here</a></li>
	    <li class="divider"></li>
	    <li><a tabindex="-1" href="#">Separated link</a></li>
	  </ul>
	</div>

  </div>
<% end %>

app/views/tickets/_responses.erb
<% @ticket_responses.each do |response| %>
	<span class="label label-success"><%= response.user ? "Agent" : "Requester" %></span>
	<span class="badge"><%= response.user ? response.user.email : response.requester.email_address %></span>
	<i><%= distance_of_time_in_words(Time.now, response.created_at) %> ago</i>
	<pre><%= response.body %></pre>
<% end %>

app/views/tickets/activity.html.erb
<h3>Recent activity</h3>
<ul>
	<% @stream.each do |stream_item| %>
		<li>
			<b><%= stream_item.class.name %></b><br />			
			<i><%= time_ago_in_words stream_item.created_at %> ago</i></br />
		</li>
	<% end %>
</ul>

app/views/tickets/index.html.erb
<h1>Tickets</h1>
<% if !@tickets.empty? %>
	<table class="table table-bordered">
	  <tr>
		<th>Age</th>
	    <th>Subject</th>
	    <th>Requester</th>
	    <th>State</th>
	    <th></th>
	  </tr>

	<% @tickets.each do |ticket| %>
	  <tr <%= ticket.state == "new" || ticket.state == "need_response" ? " class=warning" : "class=success" %>>
	    <td><%= distance_of_time_in_words(Time.now, ticket.created_at) %></td>
	    <td><%= link_to ticket.subject[0..28], ticket %></td>
	    <td><%= ticket.requester.email_address %></td>
	    <td><span class="label"><%= ticket.state %></span></td>
	    <td><%= check_box("post", "validated") %></td>
	  </tr>
	<% end %>
	</table>

	<br />

	<div class="actions pull-right">
		<div class="btn-group">
		  <a href="<%= new_ticket_path %>"><button class="btn btn-primary" type="button">New Ticket</button></a>
		  <button class="btn">Action</button>
		  <button class="btn dropdown-toggle" data-toggle="dropdown">
		    <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu">
		    <li><a tabindex="-1" href="@">Close Selected</a></li>
		    <li><a tabindex="-1" href="#">Delete Selected</a></li>
		    <li><a tabindex="-1" href="#">Something else here</a></li>
		    <li class="divider"></li>
		    <li><a tabindex="-1" href="#">Separated link</a></li>
		  </ul>
		</div>
		
<% else %>
	No tickets	
<% end %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

app/views/tickets/show.html.erb
<% if notice %><p id="notice" class="alert alert-success"><%= notice %></p><% end %>

<p>
  <h3><%= @ticket.subject %></h3>
  <span class="label label-info"><%= @ticket.state %></span>
  <%= pluralize(@ticket_responses.count, "response")%>

</p>

<span class="label label-success"><%= @ticket.user ? "Agent" : "Requester" %></span>
<span class="badge"><%= @ticket.requester.email_address %></span>
<i><%= distance_of_time_in_words(Time.now, @ticket.created_at) %> ago</i>
<pre><%= @ticket.body %></pre>

<br />

<%= render 'responses' %>

<%= render 'response_form' %>